import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import SocialLinks from "@/components/server/SocialLinks";
import Footer from "@/components/server/Footer";
import ContextProvider from "@/components/client/ContextProvider";
import Header from "@/components/client/Header";
import { getSession } from "@/lib/actions";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: any = await getSession();
  return (
    <html lang="en" className={inter.className}>
      {/* <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap"
        rel="stylesheet"
      /> */}

      <body className="tracking-wider">
        <ContextProvider>
          <Header session={session} />
          {/* <div className="h-[200vh] bg-amber-300">check sticky element</div> */}
          {children}
          <SocialLinks />
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
