import Discount from "@/components/ui/Discount";
import type { Metadata } from "next";
import NavBar from "@/components/ui/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      {/* <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap"
        rel="stylesheet"
      /> */}

      <body>
        <Discount />
        <NavBar />
        {/* <div className="h-[200vh] bg-amber-300">check sticky element</div> */}
        {children}
      </body>
    </html>
  );
}
